// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void MenuPrev_Animation(lv_obj_t * TargetObject, int delay);
void MenuNext_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
void ui_event_BtnBack(lv_event_t * e);
extern lv_obj_t * ui_BtnBack;
extern lv_obj_t * ui_BtnBackLabel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_BPMValue1;
extern lv_obj_t * ui_BPM1;
extern lv_obj_t * ui_BtnStop;
extern lv_obj_t * ui_BtnStopLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
void ui_event_BtnMenu1(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu1;
extern lv_obj_t * ui_LabelBtnMenu1;
extern lv_obj_t * ui_ImageBtnMenu1;
void ui_event_BtnMenu2(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu2;
extern lv_obj_t * ui_LabelBtnMenu2;
extern lv_obj_t * ui_ImageBtnMenu2;
void ui_event_BtnMenu3(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu3;
extern lv_obj_t * ui_LabelBtnMenu3;
extern lv_obj_t * ui_ImageBtnMenu3;
void ui_event_BtnMenu4(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu4;
extern lv_obj_t * ui_LabelBtnMenu4;
extern lv_obj_t * ui_ImageBtnMenu4;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_BtnBack2(lv_event_t * e);
extern lv_obj_t * ui_BtnBack2;
extern lv_obj_t * ui_BtnBackLabel2;
void ui_event_BtnChange(lv_event_t * e);
extern lv_obj_t * ui_BtnChange;
extern lv_obj_t * ui_BtnChangeLabel;
void ui_event_BtnStartStop(lv_event_t * e);
extern lv_obj_t * ui_BtnStartStop;
extern lv_obj_t * ui_BtnStartStopLabel;
extern lv_obj_t * ui_LabelRecordingModeI;
extern lv_obj_t * ui_LabelResultI;
extern lv_obj_t * ui_ArcTime;
extern lv_obj_t * ui_LabelResult;
extern lv_obj_t * ui_LabelMode;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Spinner4;
extern lv_obj_t * ui_Label1;
void ui_event_BtnBack3(lv_event_t * e);
extern lv_obj_t * ui_BtnBack3;
extern lv_obj_t * ui_BtnBackLabel3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Spinner3;
extern lv_obj_t * ui_Label4;
void ui_event_BtnBack4(lv_event_t * e);
extern lv_obj_t * ui_BtnBack4;
extern lv_obj_t * ui_BtnBackLabel4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_568960143);    // assets/neural-network.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
