// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_screen_menu(lv_event_t * e);
void ui_screen_ECG_free(lv_event_t * e);
void ui_screen_ECG(lv_event_t * e);
void ui_screen_3(lv_event_t * e);
void ui_screen_4(lv_event_t * e);
void ui_screen_5(lv_event_t * e);
void ui_screen_3_free(lv_event_t * e);
void polygraph_change(lv_event_t * e);
void polygraph_start(lv_event_t * e);
void ui_scree_4_free(lv_event_t * e);
void ui_screen_5_free(lv_event_t * e);
	
extern uint8_t screen2_mode;
extern uint8_t screen2_status;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
