// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "app.h"

lv_group_t * group = NULL;
uint8_t screen2_mode = 0;
uint8_t screen2_status = 0;

void ui_screen_menu(lv_event_t * e)
{
	//UI initialization
    //ui_Screen2_screen_init();
    //lv_scr_load(ui_Screen2);
	lv_screen_load_anim(ui_Screen2, LV_SCR_LOAD_ANIM_FADE_IN, 500, 0, false);
	
	group = lv_group_create();
	lv_group_add_obj(group,ui_BtnMenu1);
	lv_group_add_obj(group,ui_BtnMenu2);
	lv_group_add_obj(group,ui_BtnMenu3);
	lv_group_add_obj(group,ui_BtnMenu4);
	lv_indev_set_group(indev_keypad,group);
	
	//Create RTOS task 
	
}

void ui_screen_ECG(lv_event_t * e)
{
	//UI initialization
    //ui_Screen1_screen_init();
	lv_screen_load_anim(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_IN, 500, 0, false);
    //lv_disp_load_scr(ui_Screen1);
	lv_group_delete(group);
	group = lv_group_create();
	
	lv_group_add_obj(group,ui_BtnBack);
	lv_group_add_obj(group,ui_BtnStop);
	lv_indev_set_group(indev_keypad,group);
	
	//Create RTOS task 
	ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xc4c4c4),LV_CHART_AXIS_SECONDARY_Y);
  lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
	lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, -400, 800);
	xTaskCreate(Chart1RefreshTask,"Chart1RefreshTask",512,NULL,1,&Chart1RefreshTaskHandle);
	
	//Hardware task
	//HAL_TIM_Base_Start_IT(&htim6);
}

void ui_screen_ECG_free(lv_event_t * e)
{
	lv_group_delete(group);
	lv_chart_remove_series(ui_Chart1,ui_Chart1_series_1);
	vTaskDelete(Chart1RefreshTaskHandle);
	//HAL_TIM_Base_Stop_IT(&htim6);
	
}


void ui_screen_3(lv_event_t * e)
{
	lv_screen_load_anim(ui_Screen3, LV_SCR_LOAD_ANIM_FADE_IN, 500, 0, false);
	lv_group_delete(group);
	group = lv_group_create();
	
	lv_group_add_obj(group,ui_BtnBack2);
	lv_group_add_obj(group,ui_BtnChange);
	lv_group_add_obj(group,ui_BtnStartStop);
	lv_indev_set_group(indev_keypad,group);
	
}

void ui_screen_4(lv_event_t * e)
{
	lv_screen_load_anim(ui_Screen4, LV_SCR_LOAD_ANIM_FADE_IN, 500, 0, false);
	lv_group_delete(group);
	group = lv_group_create();
	
	lv_group_add_obj(group,ui_BtnBack3);
	lv_indev_set_group(indev_keypad,group);
}

void ui_screen_5(lv_event_t * e)
{
	lv_screen_load_anim(ui_Screen5, LV_SCR_LOAD_ANIM_FADE_IN, 500, 0, false);
	lv_group_delete(group);
	group = lv_group_create();
	
	lv_group_add_obj(group,ui_BtnBack4);
	lv_indev_set_group(indev_keypad,group);
}

void ui_screen_3_free(lv_event_t * e)
{
	lv_group_delete(group);
}

void ui_scree_4_free(lv_event_t * e)
{
	lv_group_delete(group);
}

void ui_screen_5_free(lv_event_t * e)
{
	lv_group_delete(group);
}



void polygraph_change(lv_event_t * e)
{
	 if(screen2_mode == 0)
	 {
		 _ui_label_set_property(ui_LabelMode, _UI_LABEL_PROPERTY_TEXT, "Polygraph");
		screen2_mode = 1; 
	 }
	 else if(screen2_mode == 1)
	 {
		 _ui_label_set_property(ui_LabelMode, _UI_LABEL_PROPERTY_TEXT, "Base Line");
		 screen2_mode = 0;
	 }
}

void polygraph_start(lv_event_t * e)
{
	if(screen2_status == 0)
	{
		//Start get data and reasoning
		_ui_arc_increment(ui_ArcTime,100);
	}
	else
	{
		
	}
}
