// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x101018), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner3 = lv_spinner_create(ui_Screen5);
    //lv_spinner_set_anim_params(ui_Spinner3, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 80);
    lv_obj_set_height(ui_Spinner3, 80);
    lv_obj_set_x(ui_Spinner3, -7);
    lv_obj_set_y(ui_Spinner3, -33);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 50);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Working on it");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack4 = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_BtnBack4, 60);
    lv_obj_set_height(ui_BtnBack4, 32);
    lv_obj_set_x(ui_BtnBack4, -120);
    lv_obj_set_y(ui_BtnBack4, -95);
    lv_obj_set_align(ui_BtnBack4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnBack4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnBack4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBack4, lv_color_hex(0x316D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBack4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBackLabel4 = lv_label_create(ui_BtnBack4);
    lv_obj_set_width(ui_BtnBackLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnBackLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnBackLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnBackLabel4, "Back");
    lv_obj_set_style_text_font(ui_BtnBackLabel4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack4, ui_event_BtnBack4, LV_EVENT_ALL, NULL);

}
