// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 320);
    lv_obj_set_height(ui_Panel1, 240);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_Panel1, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x131318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnMenu1 = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_BtnMenu1, 211);
    lv_obj_set_height(ui_BtnMenu1, 208);
    lv_obj_set_x(ui_BtnMenu1, -6);
    lv_obj_set_y(ui_BtnMenu1, 69);
    lv_obj_set_align(ui_BtnMenu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_scrollbar_mode(ui_BtnMenu1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_style_bg_color(ui_BtnMenu1, lv_color_hex(0x131318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnMenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_BtnMenu1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_BtnMenu1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_BtnMenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_BtnMenu1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_BtnMenu1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_BtnMenu1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelBtnMenu1 = lv_label_create(ui_BtnMenu1);
    lv_obj_set_width(ui_LabelBtnMenu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnMenu1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnMenu1, 0);
    lv_obj_set_y(ui_LabelBtnMenu1, 70);
    lv_obj_set_align(ui_LabelBtnMenu1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnMenu1, "ECG Monitor");
    lv_obj_set_style_text_color(ui_LabelBtnMenu1, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnMenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnMenu1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnMenu1 = lv_image_create(ui_BtnMenu1);
    lv_image_set_src(ui_ImageBtnMenu1, &ui_img_568960143);
    lv_obj_set_width(ui_ImageBtnMenu1, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_ImageBtnMenu1, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_ImageBtnMenu1, 0);
    lv_obj_set_y(ui_ImageBtnMenu1, -25);
    lv_obj_set_align(ui_ImageBtnMenu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnMenu1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnMenu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnMenu2 = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_BtnMenu2, 200);
    lv_obj_set_height(ui_BtnMenu2, 208);
    lv_obj_set_x(ui_BtnMenu2, -290);
    lv_obj_set_y(ui_BtnMenu2, 27);
    lv_obj_set_align(ui_BtnMenu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenu2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnMenu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnMenu2, lv_color_hex(0x131318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnMenu2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_BtnMenu2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_BtnMenu2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelBtnMenu2 = lv_label_create(ui_BtnMenu2);
    lv_obj_set_width(ui_LabelBtnMenu2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnMenu2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnMenu2, 0);
    lv_obj_set_y(ui_LabelBtnMenu2, 70);
    lv_obj_set_align(ui_LabelBtnMenu2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnMenu2, "Polygraph");
    lv_obj_set_style_text_color(ui_LabelBtnMenu2, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnMenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnMenu2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnMenu2 = lv_image_create(ui_BtnMenu2);
    lv_image_set_src(ui_ImageBtnMenu2, &ui_img_568960143);
    lv_obj_set_width(ui_ImageBtnMenu2, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_ImageBtnMenu2, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_ImageBtnMenu2, 0);
    lv_obj_set_y(ui_ImageBtnMenu2, -25);
    lv_obj_set_align(ui_ImageBtnMenu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnMenu2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnMenu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnMenu3 = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_BtnMenu3, 200);
    lv_obj_set_height(ui_BtnMenu3, 208);
    lv_obj_set_x(ui_BtnMenu3, -3);
    lv_obj_set_y(ui_BtnMenu3, -133);
    lv_obj_set_align(ui_BtnMenu3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenu3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnMenu3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnMenu3, lv_color_hex(0x131318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenu3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnMenu3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_BtnMenu3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_BtnMenu3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelBtnMenu3 = lv_label_create(ui_BtnMenu3);
    lv_obj_set_width(ui_LabelBtnMenu3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnMenu3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnMenu3, 0);
    lv_obj_set_y(ui_LabelBtnMenu3, 70);
    lv_obj_set_align(ui_LabelBtnMenu3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnMenu3, "Screen3");
    lv_obj_set_style_text_color(ui_LabelBtnMenu3, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnMenu3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnMenu3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnMenu3 = lv_image_create(ui_BtnMenu3);
    lv_image_set_src(ui_ImageBtnMenu3, &ui_img_568960143);
    lv_obj_set_width(ui_ImageBtnMenu3, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_ImageBtnMenu3, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_ImageBtnMenu3, 0);
    lv_obj_set_y(ui_ImageBtnMenu3, -25);
    lv_obj_set_align(ui_ImageBtnMenu3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnMenu3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnMenu3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnMenu4 = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_BtnMenu4, 200);
    lv_obj_set_height(ui_BtnMenu4, 208);
    lv_obj_set_x(ui_BtnMenu4, -3);
    lv_obj_set_y(ui_BtnMenu4, -133);
    lv_obj_set_align(ui_BtnMenu4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenu4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnMenu4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnMenu4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnMenu4, lv_color_hex(0x131318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnMenu4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnMenu4 = lv_label_create(ui_BtnMenu4);
    lv_obj_set_width(ui_LabelBtnMenu4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnMenu4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnMenu4, 0);
    lv_obj_set_y(ui_LabelBtnMenu4, 70);
    lv_obj_set_align(ui_LabelBtnMenu4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnMenu4, "Screen4");
    lv_obj_set_style_text_color(ui_LabelBtnMenu4, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnMenu4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnMenu4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnMenu4 = lv_image_create(ui_BtnMenu4);
    lv_image_set_src(ui_ImageBtnMenu4, &ui_img_568960143);
    lv_obj_set_width(ui_ImageBtnMenu4, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_ImageBtnMenu4, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_ImageBtnMenu4, 0);
    lv_obj_set_y(ui_ImageBtnMenu4, -25);
    lv_obj_set_align(ui_ImageBtnMenu4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnMenu4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnMenu4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BtnMenu1, ui_event_BtnMenu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenu2, ui_event_BtnMenu2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenu3, ui_event_BtnMenu3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenu4, ui_event_BtnMenu4, LV_EVENT_ALL, NULL);

}
