// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x101018), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner4 = lv_spinner_create(ui_Screen4);
    //lv_spinner_set_anim_params(ui_Spinner4, 1000, 90);
    lv_obj_set_width(ui_Spinner4, 80);
    lv_obj_set_height(ui_Spinner4, 80);
    lv_obj_set_x(ui_Spinner4, 0);
    lv_obj_set_y(ui_Spinner4, -35);
    lv_obj_set_align(ui_Spinner4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner4, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 50);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Working on it");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack3 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_BtnBack3, 60);
    lv_obj_set_height(ui_BtnBack3, 32);
    lv_obj_set_x(ui_BtnBack3, -120);
    lv_obj_set_y(ui_BtnBack3, -95);
    lv_obj_set_align(ui_BtnBack3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnBack3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnBack3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBack3, lv_color_hex(0x316D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBack3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBackLabel3 = lv_label_create(ui_BtnBack3);
    lv_obj_set_width(ui_BtnBackLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnBackLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnBackLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnBackLabel3, "Back");
    lv_obj_set_style_text_font(ui_BtnBackLabel3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack3, ui_event_BtnBack3, LV_EVENT_ALL, NULL);

}
