// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x131318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 260);
    lv_obj_set_height(ui_Chart1, 160);
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, 15);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 500);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, -8192, 8192);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, -8192, 8192);
    lv_chart_set_div_line_count(ui_Chart1, 50, 50);

    ui_Chart1_Xaxis = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart1_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart1_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart1_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart1_Xaxis, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Xaxis, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_Chart1_Xaxis, false);
    ui_Chart1_Yaxis1 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart1_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart1,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart1_Yaxis1,  -8192, 8192);
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis1, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Yaxis1, false);
    ui_Chart1_Yaxis2 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart1_Yaxis2,  -8192, 8192);
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Yaxis2, false);

    lv_obj_set_style_size(ui_Chart1, 0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart1, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_BtnBack = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_BtnBack, 60);
    lv_obj_set_height(ui_BtnBack, 32);
    lv_obj_set_x(ui_BtnBack, -120);
    lv_obj_set_y(ui_BtnBack, -95);
    lv_obj_set_align(ui_BtnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBack, lv_color_hex(0x316D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBackLabel = lv_label_create(ui_BtnBack);
    lv_obj_set_width(ui_BtnBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnBackLabel, "Back");
    lv_obj_set_style_text_font(ui_BtnBackLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 148);
    lv_obj_set_height(ui_Container1, 22);
    lv_obj_set_x(ui_Container1, 73);
    lv_obj_set_y(ui_Container1, -95);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BPMValue1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_BPMValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BPMValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BPMValue1, -20);
    lv_obj_set_y(ui_BPMValue1, 0);
    lv_obj_set_align(ui_BPMValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BPMValue1, "60");
    lv_obj_set_style_text_color(ui_BPMValue1, lv_color_hex(0xB2B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPMValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPM1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_BPM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BPM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BPM1, -55);
    lv_obj_set_y(ui_BPM1, 0);
    lv_obj_set_align(ui_BPM1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BPM1, "BPM:");
    lv_obj_set_style_text_color(ui_BPM1, lv_color_hex(0xB2B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPM1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnStop = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_BtnStop, 60);
    lv_obj_set_height(ui_BtnStop, 32);
    lv_obj_set_x(ui_BtnStop, -52);
    lv_obj_set_y(ui_BtnStop, -95);
    lv_obj_set_align(ui_BtnStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnStop, lv_color_hex(0x316D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnStopLabel = lv_label_create(ui_BtnStop);
    lv_obj_set_width(ui_BtnStopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnStopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnStopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnStopLabel, "Stop");
    lv_obj_set_style_text_font(ui_BtnStopLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack, ui_event_BtnBack, LV_EVENT_ALL, NULL);

}
