// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x101018), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack2 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_BtnBack2, 60);
    lv_obj_set_height(ui_BtnBack2, 32);
    lv_obj_set_x(ui_BtnBack2, -125);
    lv_obj_set_y(ui_BtnBack2, -99);
    lv_obj_set_align(ui_BtnBack2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnBack2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnBack2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBack2, lv_color_hex(0x316D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBack2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBackLabel2 = lv_label_create(ui_BtnBack2);
    lv_obj_set_width(ui_BtnBackLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnBackLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnBackLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnBackLabel2, "Back");
    lv_obj_set_style_text_font(ui_BtnBackLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnChange = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_BtnChange, 88);
    lv_obj_set_height(ui_BtnChange, 32);
    lv_obj_set_x(ui_BtnChange, -46);
    lv_obj_set_y(ui_BtnChange, -99);
    lv_obj_set_align(ui_BtnChange, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnChange, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnChange, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnChange, lv_color_hex(0x316D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnChange, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnChangeLabel = lv_label_create(ui_BtnChange);
    lv_obj_set_width(ui_BtnChangeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnChangeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnChangeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnChangeLabel, "Change");
    lv_obj_set_style_text_font(ui_BtnChangeLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnStartStop = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_BtnStartStop, 88);
    lv_obj_set_height(ui_BtnStartStop, 32);
    lv_obj_set_x(ui_BtnStartStop, 46);
    lv_obj_set_y(ui_BtnStartStop, -99);
    lv_obj_set_align(ui_BtnStartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnStartStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnStartStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnStartStop, lv_color_hex(0x316D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnStartStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnStartStopLabel = lv_label_create(ui_BtnStartStop);
    lv_obj_set_width(ui_BtnStartStopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnStartStopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnStartStopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnStartStopLabel, "Start");
    lv_obj_set_style_text_font(ui_BtnStartStopLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRecordingModeI = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelRecordingModeI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRecordingModeI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRecordingModeI, -45);
    lv_obj_set_y(ui_LabelRecordingModeI, 106);
    lv_obj_set_align(ui_LabelRecordingModeI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRecordingModeI, "Recording Mode:");

    ui_LabelResultI = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelResultI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelResultI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelResultI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelResultI, "Result:");
    lv_obj_set_style_text_font(ui_LabelResultI, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTime = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_ArcTime, 180);
    lv_obj_set_height(ui_ArcTime, 180);
    lv_obj_set_x(ui_ArcTime, 0);
    lv_obj_set_y(ui_ArcTime, 25);
    lv_obj_set_align(ui_ArcTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ArcTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_range(ui_ArcTime, 0, 500);
    lv_arc_set_value(ui_ArcTime, 0);

    lv_obj_set_style_arc_color(ui_ArcTime, lv_color_hex(0x316D7B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTime, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTime, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTime, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelResult = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelResult, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelResult, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelResult, 0);
    lv_obj_set_y(ui_LabelResult, 35);
    lv_obj_set_align(ui_LabelResult, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelResult, "None");
    lv_obj_set_style_text_font(ui_LabelResult, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMode = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMode, 65);
    lv_obj_set_y(ui_LabelMode, 106);
    lv_obj_set_align(ui_LabelMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMode, "Base Line");

    lv_obj_add_event_cb(ui_BtnBack2, ui_event_BtnBack2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnChange, ui_event_BtnChange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnStartStop, ui_event_BtnStartStop, LV_EVENT_ALL, NULL);

}
